// Code generated by gobind. DO NOT EDIT.

// JNI function headers for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java github.com/xtls/libxray/cgo_bridge

#ifndef __Cgo_bridge_H__
#define __Cgo_bridge_H__

#include <jni.h>

#endif
