// Code generated by gobind. DO NOT EDIT.

// JNI functions for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java github.com/xtls/libxray/cgo_bridge

#include <android/log.h>
#include <stdint.h>
#include "seq.h"
#include "_cgo_export.h"
#include "cgo_bridge.h"


JNIEXPORT void JNICALL
Java_cgo_1bridge_Cgo_1bridge__1init(JNIEnv *env, jclass _unused) {
	jclass clazz;
}

JNIEXPORT jstring JNICALL
Java_cgo_1bridge_Cgo_bridge_invoke(JNIEnv* env, jclass _clazz, jstring requestJSON) {

    fprintf(stderr, "JNI INVOKE: 1 BEFORE go_seq_from_java_string\n");
    fflush(stderr);

    nstring _requestJSON = go_seq_from_java_string(env, requestJSON);

    fprintf(stderr, "JNI INVOKE: 2 AFTER go_seq_from_java_string len=%d\n",
            (int)_requestJSON.len);
    fflush(stderr);

    fprintf(stderr, "JNI INVOKE: 3 BEFORE proxycgo_bridge__Invoke\n");
    fflush(stderr);

    nstring r0 = proxycgo_bridge__Invoke(_requestJSON);

    fprintf(stderr, "JNI INVOKE: 4 AFTER proxycgo_bridge__Invoke len=%d\n",
            (int)r0.len);
    fflush(stderr);

    fprintf(stderr, "JNI INVOKE: 5 BEFORE go_seq_to_java_string\n");
    fflush(stderr);

    jstring _r0 = go_seq_to_java_string(env, r0);

    fprintf(stderr, "JNI INVOKE: 6 AFTER go_seq_to_java_string\n");
    fflush(stderr);

    return _r0;
}

