// Code generated by gobind. DO NOT EDIT.

// JNI functions for the Go <=> Java bridge.
//
//   autogenerated by gobind -lang=java github.com/xtls/libxray/cgo_bridge

#include <android/log.h>
#include <stdint.h>
#include "seq.h"
#include "_cgo_export.h"
#include "cgo_bridge.h"


JNIEXPORT void JNICALL
Java_cgo_1bridge_Cgo_1bridge__1init(JNIEnv *env, jclass _unused) {
	jclass clazz;
}

JNIEXPORT jstring JNICALL
Java_cgo_1bridge_Cgo_1bridge_invoke(JNIEnv* env, jclass _clazz, jstring requestJSON) {
	nstring _requestJSON = go_seq_from_java_string(env, requestJSON);
	nstring r0 = proxycgo_bridge__Invoke(_requestJSON);
	jstring _r0 = go_seq_to_java_string(env, r0);
	return _r0;
}

