// Code generated by gobind. DO NOT EDIT.

// Package main is an autogenerated binder stub for package cgo_bridge.
//
//	autogenerated by gobind -lang=go github.com/xtls/libxray/cgo_bridge
package main

/*
#include <stdlib.h>
#include <stdint.h>
#include "seq.h"
#include "cgo_bridge.h"

*/
import "C"

import (
	"github.com/xtls/libxray/cgo_bridge"
	_seq "golang.org/x/mobile/bind/seq"
)

// suppress the error if seq ends up unused
var _ = _seq.FromRefNum

//export proxycgo_bridge__Invoke
func proxycgo_bridge__Invoke(param_requestJSON C.nstring) C.nstring {
	_param_requestJSON := decodeString(param_requestJSON)
	res_0 := cgo_bridge.Invoke(_param_requestJSON)
	_res_0 := encodeString(res_0)
	return _res_0
}
