// Code generated by gobind. DO NOT EDIT.

// Java class cgo_bridge.Cgo_bridge is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/xtls/libxray/cgo_bridge
package cgo_bridge;

import go.Seq;

public abstract class Cgo_bridge {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Cgo_bridge() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native String invoke(String requestJSON);
}
